//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morse_Tutor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Morse_Tutor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap morse_code {
            get {
                object obj = ResourceManager.GetObject("morse_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///of
        ///and
        ///to
        ///a
        ///in
        ///that
        ///I
        ///was
        ///he
        ///his
        ///with
        ///is
        ///it
        ///for
        ///as
        ///had
        ///you
        ///not
        ///be
        ///on
        ///at
        ///by
        ///her
        ///which
        ///have
        ///or
        ///from
        ///this
        ///but
        ///all
        ///him
        ///she
        ///were
        ///they
        ///my
        ///are
        ///so
        ///me
        ///their
        ///an
        ///one
        ///de
        ///we
        ///who
        ///would
        ///said
        ///been
        ///no
        ///He
        ///will
        ///them
        ///when
        ///if
        ///there
        ///more
        ///out
        ///And
        ///It
        ///any
        ///up
        ///into
        ///your
        ///has
        ///do
        ///what
        ///could
        ///but
        ///our
        ///than
        ///other
        ///some
        ///very
        ///man
        ///upon
        ///about
        ///its
        ///only
        ///time
        ///may
        ///la
        ///like
        ///little
        ///then
        ///now
        ///should
        ///can
        ///made
        ///did
        ///such
        ///A
        ///great
        ///In
        ///must
        ///these
        ///two
        ///before
        ///see
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string top_100_words {
            get {
                return ResourceManager.GetString("top_100_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string top100Words {
            get {
                return ResourceManager.GetString("top100Words", resourceCulture);
            }
        }
    }
}
